---
- name: "Include tasks for Puppet 5 for {{ ansible_distribution }}"
  include_tasks: "puppet-5.yml"
  when: puppet_version_install|int == 5

- name: Include tasks for Puppet for {{ ansible_distribution }}
  include_tasks: "puppet.yml"
  when: puppet_version_install|int < 5

- name: Add Java Backport
  shell: 'echo "deb http://ftp.debian.org/debian jessie-backports main" > /etc/apt/sources.list.d/jessie-backports.list'
  when: ansible_distribution_release == "Jessie" and puppet_version|int == 5

- name: Install Java Backport
  apt:
    dpkg_options: force-confdef,force-confold,-t jessie-backports
    name: openjdk-8-jdk-headless
    state: present
  when: ansible_distribution_release == "Jessie" and puppet_version|int == 5

- name: Set default Java
  shell: update-alternatives --set java /usr/lib/jvm/java-8-openjdk-amd64/jre/bin/java
  when: ansible_distribution_release == "Jessie" and puppet_version|int == 5
