---
- name: "Download puppet package for {{ ansible_distribution }} - {{ ansible_distribution_release }}"
  shell: wget "https://apt.puppetlabs.com/puppetlabs-release-{{ ansible_distribution_release }}.deb"
  args:
    chdir: "/root"

- name: "Install puppet package for {{ ansible_distribution }} - {{ ansible_distribution_release }}"
  shell: "dpkg -i --no-triggers /root/puppetlabs-release-{{ ansible_distribution_release }}.deb && apt-get update"
  args:
    chdir: "/root"

- name: "Remove downloaded file."
  file:
    path: "/root/puppetlabs-release-{{ ansible_distribution_release }}.deb"
    state: absent

- name: Install Puppet Server
  package:
    name: puppetserver

- name: Start puppet service
  service:
    name: puppetserver
    enabled: yes
    state: started
