---
- name: Configure CA Master
  shell: "{{ puppet_binary }} config set {{ item.key }} {{ item.value }}"
  with_dict: "{{ puppet_ca_master }}"

- name: Create certificates for Non-CA Masters
  shell: "{{ puppet_binary }} cert generate {{ item.hostname }} --dns_alt_names={{ item.alt_dns_names }} ; true"
  with_items: "{{ puppet_non_ca_masters }}"
  when: puppet_non_ca_masters
  ignore_errors: yes

- name: Download public key from CA master
  fetch:
    dest: "{{ local_certificates_directory }}/public_keys/"
    src: "/var/lib/puppet/ssl/public_keys/{{ item.hostname }}.pem"
    flat: yes
  with_items: "{{ puppet_non_ca_masters }}"
  when: puppet_non_ca_masters

- name: Download private key from CA master
  fetch:
    dest: "{{ local_certificates_directory }}/private_keys/"
    src: "/var/lib/puppet/ssl/private_keys/{{ item.hostname }}.pem"
    flat: yes
  with_items: "{{ puppet_non_ca_masters }}"
  when: puppet_non_ca_masters
