---
# Perform any distribution specific tasks
- include_tasks: "{{ ansible_os_family }}/main.yml"

- name: Install Puppet server
  package:
    name: puppetserver

# Test
- name: Enable autosigning for select hosts
  template:
    dest: /etc/puppet/autosign.conf
    src: autosign.conf.j2
    owner: puppet
    follow: no
    group: puppet
  when: puppet_autosign_certificates

- include_tasks: "ca-master.yml"
  when: puppet_ca_master.certname == ansible_fqdn

- include_tasks: "non-ca-masters.yml"
  when: puppet_non_ca_masters and puppet_ca_master.certname != ansible_fqdn

- name: Installing puppet modules
  shell: "puppet module install {{ item.name }} --version={{ item.version }}"
  with_items: "{{ puppet_modules }}"
  when: puppet_modules

- name: Restore file contexts
  shell: restorecon -r /etc
  when: ansible_selinux['status'] == 'enforcing'

# To do: add modules

- name: Start puppet server
  service:
    name: puppetserver
    enabled: yes
    state: started
