---
# Perform any distribution specific tasks
- name: Including tasks for OS.
  include: "{{ ansible_os_family }}/main.yml"

- include: "ca-master.yml"
  when: puppet_ca_master.certname == ansible_fqdn

- include: "non-ca-masters.yml"
  when: puppet_non_ca_masters and puppet_ca_master.certname != ansible_fqdn

- name: Installing puppet modules
  shell: "{{ puppet_binary }} module install {{ item.name }} --version={{ item.version }}"
  with_items: "{{ puppet_modules }}"
  when: puppet_modules

- name: Restore file contexts
  shell: restorecon -r /etc
  when: ansible_selinux['status'] == 'enforcing'
