---
# Perform any distribution specific tasks
- name: Including tasks for OS.
  include: "{{ ansible_distribution }}/main.yml"

- name: Including specific puppet tasks
  include: "{{ ansible_distribution }}/puppet.yml"
  when: puppet_version_install|int < 5

- name: Including specific puppet5 tasks
  include: "{{ ansible_distribution }}/puppet-5.yml"
  when: puppet_version_install|int == 5

- name: Set puppet binary
  set_fact:
    puppet_binary: /opt/puppetlabs/bin/puppet
  when: puppet_version_install|int == 5

- include: "ca-master.yml"
  when: puppet_ca_master.certname == ansible_fqdn

- include: "non-ca-masters.yml"
  when: puppet_non_ca_masters and puppet_ca_master.certname != ansible_fqdn

- name: Installing puppet modules
  shell: "{{ puppet_binary }} module install {{ item.name }} --version={{ item.version }}"
  with_items: "{{ puppet_modules }}"
  when: puppet_modules

- name: Restore file contexts
  shell: restorecon -r /etc
  when: ansible_selinux['status'] == 'enforcing'

- name: Start puppet server
  service:
    name: puppetserver
    enabled: yes
    state: started
